# Generated by Django 6.0.2 on 2026-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_coordinator_course_subject_subjectassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('seminar_hall', 'Seminar Hall'), ('tutorial_room', 'Tutorial Room'), ('lecture_hall', 'Lecture Hall'), ('lab', 'Lab'), ('auditorium', 'Auditorium')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
    ]
